### ISSUE TITLE
v129 chrome os

### ISSUE THREAD

**Issue by ipushthecarts** [FWSmasher/rigtools#7]
ik this might not be possible, but I do have to ask, would it be possible at all to have an updated version of rigtools that would work with v129, or is it completely patched and wont be coming back, I personally am in v129,well I just updated it thismorning and it worked fine, but I accidentally closed the tab and couldn't get it back, so would it be possible to update it, or is it completely patched? thank you!

**Comment by MunyDev** [comment]
Sorry, its not possible.
